spring.application.name=gestion-produits

# Configuration de la base de données H2
spring.datasource.url=jdbc:h2:mem:ecomm_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password


# Configuration JPA
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

spring.mvc.dispatch-options-request=true
spring.jpa.properties.hibernate.legacy_limit_handler = true







